[package]
edition = "2021"
name = "spotify-rust"
version = "0.1.0"

[dependencies]
futures = "0.3.31"
reqwest = {version = "0.12.12", features = ["json"]}
serde = {version = "1.0.217", features = ["derive"]}
serde_json = "1.0.138"
tokio = {version = "1.43.0", features = ["full"]}